#---------------------------
# Fluid
# Author: Fluid-dev organization
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# Docs：https://hexo.fluid-dev.com/docs/guide/
#---------------------------

#---------------------------
# 全局
# Site
#---------------------------

# 网站标签页的 icon
favicon: /img/favicon.png

# 用于苹果设备的 icon
apple_touch_icon: /img/apple-touch-icon.png

# 浏览器标签页中的标题分隔符
title_join_string: ' - '

navbar:
  # 导航栏左侧的标题，为空则按 hexo config.title 显示
  title:

  # 菜单列表，可自行增减
  # key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值
  # icon 是 css class，可以省略
  # 增加 name 可以强制显示指定名称
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'archive', link: '/archives/', icon: 'iconfont icon-archive-fill' }
    - { key: 'category', link: '/categories/', icon: 'iconfont icon-category-fill' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    #- { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill' } # 关于页，需要 `hexo new page about `手动创建
    #- { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }  # 友链页，需要 `hexo new page links` 手动创建

  # 搜索
  search:
    enable: true
    # 元数据地址，可用外链
    path: /local-search.xml
    field: post
    content: true

# 页脚
footer:
  # 统计网站 PV、UV，基于不蒜子
  statistics:
    enable: false
    # 显示的文本，{}是数字的占位符（必须包含)，下同
    pv_format: "总访问量 {} 次"
    uv_format: "总访客数 {} 人"

  # Only for Mainland Chinese user
  beian:
    enable: false
    # ICP证号
    icp_text: 京ICP证123456号
    # 公安备案号，不填则只显示ICP
    police_text: 京公网安备12345678号
    # 公安备案的编号，用于URL跳转查询
    police_code: 12345678
    # 公安备案的图片，为空时不显示备案图片
    police_icon: /img/police_beian.png

# 社交资料
# 更多图标可从 https://github.com/fluid-dev/static/blob/master/hexo-theme-fluid/iconfont.png 查找，class 代表图标的 css class
social_links:
  - { class: 'iconfont icon-github-fill', link: 'https://github.com' }
  - { class: 'iconfont icon-douban-fill', link: 'https://github.com' }
  # 添加 pop 后，点击不再跳转，而是悬浮二维码，需要指定 image
  - { class: 'iconfont icon-wechat-fill', pop: '/img/favicon.png' }

# 代码高亮
highlight:
  enable: true
  theme: tomorrow-night-eighties
  # 是否开启复制代码的按钮
  copy_btn: true

# 主题配色
# 不一定能每一处都生效，可能会被局部样式覆盖，这种情况建议用自定义 css 解决
# 可以在这获得启发： https://www.webdesignrankings.com/resources/lolcolors/
color:
  # body 背景色
  body_bg_color: "#eee"
  # 顶部菜单背景色
  navbar_bg_color: "#2f4154"
  # 顶部菜单字体色
  navbar_text_color: "white"
  # 全局字体色
  text_color: "#3c4858"
  # 全局次级字体色（摘要、简介等位置）
  sec_text_color: "#718096"
  # 文章正文字体色
  post_text_color: "#2c3e50"
  # 文章标题标签字体色（h1 h2 h3...）
  post_heading_color: "#1a202c"
  # 超链接字体色
  link_color: "#3c4858"
  # 超链接悬浮时字体色
  link_hover_color: "#1abc9c"
  # 超链接悬浮背景色
  link_hover_bg_color: "#ebedef"
  # 主面板背景色
  board_color: "#fff"

# 主题字体配置
font:
  # 字号
  font_size: 16px
  # 字体
  font_family:
  # 代码的字号
  code_font_size: 85%

# 网页访问统计
web_analytics:
  enable: false
  # 百度统计的Key（hm.js? 后边的字符串）
  baidu:
  # Google统计的Tracking ID，参见 https://analytics.google.com/analytics/web/
  google:
  # 腾讯统计的H5 App id，参见 https://mta.qq.com/h5/manage/ctr_app_manage (开启高级功能才有cid)
  tencent:
    sid:
    cid:
  # 腾讯统计早期版站点统计sID，参见 https://ta.qq.com/#/site/list
  tajs:
  # 51.la站点统计ID，参见 https://www.51.la/user/site/index
  woyaola:
  # 友盟/cnzz站点统计web_id，参见 https://web.umeng.com/main.php?c=site&a=show
  cnzz:

# 为 subtitle 添加打字机效果
typing:
  enable: true
  # 打印速度，数字越大越慢
  typeSpeed: 70
  # 游标字符
  cursorChar: "_"
  # 是否循环播放效果
  loop: false

# 为标题添加锚图标
anchorjs:
  enable: true
  element: h1,h2,h3,h4,h5,h6
  # 图标位置： left | right
  placement: right
  # 显示方式：hover（鼠标在元素上悬浮时显示） | always（一直显示） | touch（移动端触摸显示）
  visible: hover
  # 图标：§ | # | ❡ 等，可自定义
  icon: "#"

# 鼠标点击动效
mouse_click:
  enable: false
  # 样式：values（社会主义核心价值观） | love（爱心）
  style: values

# 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）
force_https: false

# 对页面中的图片进行懒加载处理，可见范围外的图片不会加载
lazyload:
  enable: true
  # 仅在文章页使用懒加载，开启后如果自定义页面需要使用，可以在 Front-matter 里设置 `lazyload: true`
  onlypost: false

# 平滑滚动效果，服务器加载过慢可能会影响滚动，请慎用
smooth_scroll: false

# 回到顶部按钮
scroll_top_arrow: true

# 头图滚动视差
banner_parallax: true

# 指定自定义 js 文件路径，路径是相对 source 目录，如 /js/custom.js
custom_js:

# 指定自定义 css 文件路径，路径是相对 source 目录，如 /css/custom.css
custom_css:

# 自定义底部 HTML 内容（位于 footer 上方），也可用于外部引入 js css 这些操作，注意不要和 post.custom 配置冲突
custom_html:


#---------------------------
# 首页
# Index Page
#---------------------------
index:
  background: /img/default.png
  # 黑色蒙版的透明度：0 - 1.0， 0 是完全透明（无蒙版），1 是完全不透明
  background_mask_alpha: 0.3
  # 默认的文章封面图，当没有指定 index_img 时会使用该图片，若都为空则不显示任何图片
  post_default_img: ''
  # 副标题
  subtitle:

  # 文章信息
  post_meta:
    excerpt: true
    date: true
    category: true
    tag: true


#---------------------------
# 自定义页面
# Custom Page by `hexo new page ***`
#---------------------------
page:
  banner_img: /img/default.png
  # 图片高度：0 - 100
  banner_img_height: 70
  # 透明度: 0 - 1.0
  banner_mask_alpha: 0.3

  # 图片点击放大：在 Front-matter 中设置 `image_zoom: true`，并且图片插入格式应为 <img src="..." zoom />
  # 数学公式：在 Front-matter 中设置 `math: true`
  # 流程图：在 Front-matter 中设置 `mermaid: true`


#---------------------------
# 文章页
# Post Page
#---------------------------
post:
  banner_img: /img/default.png
  # 图片高度：0 - 100
  banner_img_height: 70
  # 透明度: 0 - 1.0
  banner_mask_alpha: 0.3

  # 文章元信息
  meta:
    created_date: true
    updated_date: false

    # 字数统计
    wordcount:
      enable: true
      # 显示的文本，{}是数字的占位符（必须包含)，下同
      format: "{} 字"

    # 阅读时间
    min2read:
      enable: true
      format: "{} 分钟"
      # 阅读速度，用于计算阅读时间，如果是技术文章，建议降低
      words_per_min: 100

    # 阅读次数，基于不蒜子
    views:
      enable: false
      format: "{} 次"

  toc:
    enable: true
    # 选择器
    headingSelector: h2,h3,h4,h5,h6
    # 折叠深度，0 是全部折叠，6 是全部不折叠
    collapseDepth: 0

  # 文章底部上一篇下一篇
  prev_next: true

  copyright:
    enable: true
    content: '本博客所有文章除特别声明外，均采用 <a href="https://zh.wikipedia.org/wiki/Wikipedia:CC_BY-SA_3.0%E5%8D%8F%E8%AE%AE%E6%96%87%E6%9C%AC" rel="nofollow noopener">CC BY-SA 3.0协议</a> 。转载请注明出处！'

  # 自定义页脚,支持 HTML，可插入赞赏码、公众号二维码等内容
  custom_footer:
    enable: false
    content: '<img src="/img/favicon.png">'

  # 点击放大图片
  image_zoom: true

  # 数学公式，开启之前需要更换 Markdown 渲染器，否则复杂公式会有兼容问题，具体请见：https://hexo.fluid-dev.com/docs/guide/##latex-数学公式
  math:
    enable: false
    # specific 开启后，只有在文章 Front-matter 里设置 `math: true` 才会在文章页启动公式转换，以便在页面不包含公式时提高加载速度
    specific: false
    # 公式引擎：mathjax | katex
    engine: mathjax

  # 流程图，基于 mermaid-js，文档：http://mermaid-js.github.io/mermaid/
  mermaid:
    enable: false
    # specific 开启后，只有在文章 Front-matter 里设置 `mermaid: true` 才会在文章页启动公式转换，以便在页面不包含公式时提高加载速度
    specific: false
    # 接口选项，具体可见：http://mermaid-js.github.io/mermaid/#/mermaidAPI
    options: { theme: 'default' }


#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img: /img/default.png
  # 图片高度：0 - 100
  banner_img_height: 70
  # 透明度: 0 - 1.0
  banner_mask_alpha: 0.3
  # 副标题
  subtitle:


#---------------------------
# 分类页
# Categories Page
#---------------------------
category:
  banner_img: /img/default.png
  # 图片高度：0 - 100
  banner_img_height: 70
  # 透明度: 0 - 1.0
  banner_mask_alpha: 0.3
  # 副标题
  subtitle:


#---------------------------
# 标签页
# Tags Page
#---------------------------
tag:
  banner_img: /img/default.png
  # 图片高度：0 - 100
  banner_img_height: 70
  # 透明度: 0 - 1.0
  banner_mask_alpha: 0.3
  # 副标题
  subtitle:

  # 标签云
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"


#---------------------------
# 关于页
# About Page
# hexo new page about
#---------------------------
# 以下仅为页面顶部的基本信息，更多内容请在 /source/about/index.md 中编辑，支持 markdown 和 HTML
about:
  banner_img: /img/default.png
  # 图片高度：0 - 100
  banner_img_height: 70
  # 透明度: 0 - 1.0
  banner_mask_alpha: 0.3
  # 副标题
  subtitle:
  # 头像
  avatar: /img/avatar.jpg
  # 显示的用户名
  name: myname
  # 个人标签
  tags: Student | Developer


#---------------------------
# 404页
# 404 Page
#---------------------------
notfound:
  banner_img: /img/default.png
  # 图片高度：0 - 100
  banner_img_height: 70
  # 透明度: 0 - 1.0
  banner_mask_alpha: 0.3
  # 副标题
  subtitle: 'Page not found'


#---------------------------
# 友链页
# Links Page
#---------------------------
links:
  banner_img: /img/default.png
  # 图片高度：0 - 100
  banner_img_height: 70
  # 透明度: 0 - 1.0
  banner_mask_alpha: 0.3
  # 副标题
  subtitle:
  # 友链列表，intro 与 image 可省略
  items:
    - {
      title: 'Fluid Docs',
      intro: '主题使用指南',
      link: 'https://hexo.fluid-dev.com/docs/',
      image: '/img/favicon.png'
    }
    - {
      title: 'Fluid Repo',
      intro: '主题 GitHub 仓库',
      link: 'https://github.com/fluid-dev/hexo-theme-fluid',
      image: '/img/favicon.png'
    }
    - {
      title: 'Fluid Changelog',
      intro: '主题更新日志',
      link: 'https://github.com/fluid-dev/hexo-theme-fluid/blob/master/Changelog.md',
      image: '/img/favicon.png'
    }
